### ISSUE TITLE
Feature Request: Handle linux paths 

### ISSUE THREAD

**Issue by SinghHrmn** [ravgeetdhillon/clean-downloads#2]
I tried using the tool and was trying to clean my Downloads and I provided the path to be `~/Downloads/` since it is a valid path the script must handle that. But it throws an error and here is the traceback call
```console
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    sort_folder(DOWNLOADS_DIR)
  File "main.py", line 37, in sort_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [Errno 2] No such file or directory: '~/Downloads/'
```

**Comment by ravgeetdhillon** [comment]
Hi @SinghHrmn. `~/Downloads/` is a valid path for the command line. You need to provide full path to the Downloads directory. Something like this would work: `/home/username/Downloads/`

**Comment by SinghHrmn** [comment]
@ravgeetdhillon thanks wasn't aware of that fact. And yes for most of the times I have provided the path from terminal so I thought python has a way of handling that even if provided internally.
